name: Lint
on:
  pull_request:
    branches:
      - master
      - main

jobs:
  lint:
    name: Lint
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Yarn
        run: npm install -g yarn
      - name: Installation
        run: yarn install
      - name: Lint
        run: yarn run lint
